server:
  port: 25001

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: ${PG_URL}

mybatis:
  mapper-locations: classpath:cn/darkflame/meta/mapper/**/*.xml
logging:
  level:
    com:
      example:
        mapper: debug